[package]
name = "data_type"
version = "0.1.0"
authors = ["frandy <303734023@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
